name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy

    env:
      REPOSITORY: '${{ github.repository }}'
      PATH: '.'
      URI_PATH: 'producttrap'

    steps:

      - name: Deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Docs
          repo: owenvoke/docs.voke.dev
          token: '${{ secrets.DOCS_AUTH_TOKEN }}'
          inputs: |
            {
                "repository": "${{ env.REPOSITORY }}",
                "path": "${{ env.PATH }}",
                "uri-path": "${{ env.URI_PATH }}",
                "command": "npm run prod -- --base '/producttrap/' --outDir",
                "secret-token": "${{ secrets.DOCS_TOKEN }}"
            }
